name: E2E Wallet Fund and Faucet Balance
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'E2E Wallet Fund and Faucet Balance'
  # Cron job to run faucet fund and balance every 8th hour
  schedule:
    - cron: '0 */8 * * *'

jobs:
  balance-and-fund:
    env:
      working-directory: ./packages/mobile
    name: balance-and-fund
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Run Balance and Fund
        working-directory: ${{env.working-directory}}/e2e/scripts
        run: node ./fund-e2e-accounts.ts